# Generated by Django 3.0.3 on 2020-02-11 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(blank=True, choices=[('rn', 'Registered Nurse'), ('np', 'Nurse Practioner'), ('other', 'Other')], max_length=25, verbose_name='Select Profession'),
        ),
    ]
